// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbr1wH8vOk73KpNbG44BOMrQJbfn9ERE',
    appId: '1:468877495126:web:e7d2f3cc11e151e9a7e4f7',
    messagingSenderId: '468877495126',
    projectId: 'easybuild-3275c',
    authDomain: 'easybuild-3275c.firebaseapp.com',
    storageBucket: 'easybuild-3275c.firebasestorage.app',
    measurementId: 'G-K71G6WZPGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2TFJaH_Iw79BEoqQBRem2Z3jhsYBtvPg',
    appId: '1:468877495126:android:f3f73f2c5d055ba6a7e4f7',
    messagingSenderId: '468877495126',
    projectId: 'easybuild-3275c',
    storageBucket: 'easybuild-3275c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ppu9IxWfuQ2D4nZNR-x3e0qjgDfegPI',
    appId: '1:468877495126:ios:550f28fddb21fdbaa7e4f7',
    messagingSenderId: '468877495126',
    projectId: 'easybuild-3275c',
    storageBucket: 'easybuild-3275c.firebasestorage.app',
    iosBundleId: 'com.example.pcBuildere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ppu9IxWfuQ2D4nZNR-x3e0qjgDfegPI',
    appId: '1:468877495126:ios:550f28fddb21fdbaa7e4f7',
    messagingSenderId: '468877495126',
    projectId: 'easybuild-3275c',
    storageBucket: 'easybuild-3275c.firebasestorage.app',
    iosBundleId: 'com.example.pcBuildere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGbr1wH8vOk73KpNbG44BOMrQJbfn9ERE',
    appId: '1:468877495126:web:bafaafe85b3f7bc0a7e4f7',
    messagingSenderId: '468877495126',
    projectId: 'easybuild-3275c',
    authDomain: 'easybuild-3275c.firebaseapp.com',
    storageBucket: 'easybuild-3275c.firebasestorage.app',
    measurementId: 'G-2VR4G7FKEW',
  );
}
